<!DOCTYPE html>
<?php 
$erro = "";
$sucesso = "";
$logado = false;

if (isset($_SESSION['usuario'])) {
    $logado = true;
    $sucesso = "Você já está conectado.";
}

if (isset($_SESSION['mensagem_erro'])) {
    $erro = $_SESSION['mensagem_erro'];
    unset($_SESSION['mensagem_erro']);
}
?>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Login</title>
        <link rel="stylesheet" href="resources/bootstrap/css/bootstrap.min.css">
    </head>
    <body>
        <div class="container" style="margin-top: 20px;">
            <div class="col-md-4 col-md-offset-4">
                <?php if ($erro): ?>
                    <section class="alert alert-danger text-center"><?= $erro ?></section>
                <?php endif ?>
                    <?php if ($sucesso): ?>
                    <section class="alert alert-success text-center"><?= $sucesso ?></section>
                <?php endif ?>
                <?php if (!$logado): ?>
                    <form action="/logar" method="post">
                        <input type="hidden" name="requisicao" value="logar">
                        <div class="form-group">
                            <label for="usuario">Usuário</label>
                            <input type="text" name="usuario" class="form-control" id="usuario" placeholder="Preencha o usuário">
                        </div>
                        <div class="form-group">
                            <label for="senha">Senha</label>
                            <input type="password" name="senha" class="form-control" id="senha" placeholder="Digite sua senha">
                        </div>
                        <button type="submit" class="btn btn-primary btn-block">Entrar</button>
                    </form>
                <?php else: ?>
                    <a class="btn btn-primary btn-block" href="/administrativo">Acessar administrativo</a><br>
                    <form action="requisicao.php" method="post">
                        <input type="hidden" name="requisicao" value="deslogar">
                        <button type="submit" class="btn btn-warning btn-block">Desconectar</button>
                    </form>
                <?php endif ?>
            </div>
        </div>
    </body>
</html>